---
- name: test connection
  ping:

- name: Update all packages
  apt: update_cache=yes upgrade=full
  become: true

- name: Install Japanese Language Pack
  apt: name=language-pack-ja update_cache=yes
  become: true

- name: Check timezone
  shell: grep 'Asia/Tokyo' /etc/timezone
  register: check_timezone
  failed_when: check_timezone.rc not in [0, 1]

- name: Setting timezone 1
  shell: sh -c 'echo "Asia/Tokyo" > /etc/timezone'
  become: true
  when: check_timezone.rc == 1

- name: Setting timezone 2
  shell: dpkg-reconfigure --frontend noninteractive tzdata
  become: true
  when: check_timezone.rc == 1

- name: Update locale to Japanese
  shell: update-locale LANG=ja_JP.UTF-8
  become: true
